Adops funct model/36
gii-is-psg2/psg2-2324-g5-52 pull request #42
Opened 2024-03-07 12:17 UTC by rafcarmed

Buenas, para la implementación del modelo de la funcionalidad `Adoptions`, correspondiente a la Issue #36, he hecho lo siguiente :

- He creado la carpeta adoption, en la que he creado la entidad `Adoption.java`, que representará una solicitud de adopción, tal como quedamos : originalOwner, newOwner, petToAdopt, active y description.
- He creado también la entidad `AdoptionRepository.java`, en principio con un único método, se me ha ocurrido, que devolverá la lista de todas las mascotas pendientes de adopción ( p.on_adoption = TRUE )
- He modificado la entidad mascota ( `Pet` ) para añadirle el atributo `Boolean on_adoption`, que se actualizará a TRUE cuando un propietario marque una de sus mascotas como disponible para ser adoptadas.
- A ver cómo veis las anotaciones @ManyToOne que he puesto, si es así realmente o no : he entendido que un originalOwner es @ManyToOne porque puede poner más mascotas en adopción, y newOwner también sería @ManyToOne porque puede adoptar más de una mascota, y la propia PetToAdopt como @ManyToOne porque podría volver a ser adoptada en un futuro por otro newOwner ...

He intentado crear la rama (al ser la primera desde el informe técnico) con la nomenclatura que indicamos en el Technical Report, nombre feature y terminando con el número de Issue : /XX, si no es correcto , creo que es posible renombrar la rama.

A ver cuando podáis echarle un vistazo y me decís si está bien, si está mal, faltan cosas por añadir, etc... en los comentarios.

Gracias.

2024-03-08 09:47 UTC, benjimrfl requested changes
Revisar comentarios en cada archivo

2024-03-08 09:47 UTC, benjimrfl commented on src/main/java/org/springframework/samples/petclinic/adoption/Adoption.java
Faltarían algunas anotaciones:
· @Table(name = "adoptions") -> para elegir el nombre que queremos que tenga la tabla en la DB, se pone debajo de @Entity
· Los owners y el pet deberian tener @NotNull, no queremos que falte ninguno de estos campos al crear una adoption. Tambien habria que añadir la anotación @JoinColumn(name="entity_id") para que meta el id de los owners y del pet en la tabla adoptions
· Los ManyToOne, deberian tener ManyToOne(optional = false), por lo de antes, no queremos que una adoption no este relacionada con owners o pet
· El atributo active, debe tener notación @NotNull y yo personalmente lo pondría por defecto a true, ya que cuando se crea una adoption, es que se va a poner un pet en adopción, ya cuando se finalice el proceso, pasará a false
· El atributo description deberia tener @NotEmpty, para que sea obligatorio escribir alguna description y le pondría longitud máxima.

2024-03-08 09:47 UTC, benjimrfl commented on src/main/java/org/springframework/samples/petclinic/adoption/AdoptionRepository.java
De este todo bien, creo que ese método será muy útil

2024-03-08 09:47 UTC, benjimrfl commented on src/main/java/org/springframework/samples/petclinic/pet/Pet.java
· Pondría @NotNull y que sea false por defecto, al crear un pet en la DB, si no tiene owner no se podría poner en adopción, y si un owner pone a su pet en adopción pasaría a ser true y listo

2024-03-08 19:04 UTC, rafcarmed commented on src/main/java/org/springframework/samples/petclinic/adoption/AdoptionRepository.java
De acuerdo, Benji, muchas gracias. De todas formas, he tenido que modificar la clase porque la @Query de JPQL indicada error en el arranque del Backend al usar yo en el `WHERE` el nombre de la columna de la tabla, `p.on_adoption = TRUE` en lugar del atributo de la clase Entity `p.onAdoption = TRUE`. Ya lo he actualizado también. Gracias.

2024-03-08 19:05 UTC, rafcarmed commented on src/main/java/org/springframework/samples/petclinic/pet/Pet.java
De acuerdo. Implementado y subido el cambio. Gracias.

2024-03-08 19:20 UTC, rafcarmed commented on src/main/java/org/springframework/samples/petclinic/adoption/Adoption.java
Implementados todos los cambios y subidos. Pero tras hacerlo acabo de darme cuenta de que en realidad `adoption.active` no puede ser por defecto True, sino False, Benji. En esta tabla se insertará una fila cuando un `newOwner` haga una solicitud de adopción de una mascota que esté puesta como disponible para adoptar (`pet.onAdoption=True`) pero solicitudes como esta puede haber varias para una misma mascota. Cuando `originalOwner`, el propietario, vea la lista de solicitudes para adoptar su mascota (3 solicitudes por ejemplo) y elija qué `newOwner` de los tres será el nuevo propietario, entonces se activará  `adoption.active=TRUE` de esa fila, y las otras dos filas quedarán en `adoption.active=false` para siempre, y `pet.onAdoption` también pasará entonces a ser False. Espero haberme explicado Benji, pero creo que es así. Si me confirmas cuando lo puedas leer, lo cambio a false por defecto, o lo hablamos para aclararlo. Es que igual en lugar de llamarla Activa, deberíamos llamar al atributo Admitida, admitted, para indicar que esa ha sido la adopción admitida o elegida, de entra varias.

2024-03-09 07:47 UTC, benjimrfl requested changes

2024-03-09 07:47 UTC, benjimrfl commented on src/main/java/org/springframework/samples/petclinic/adoption/Adoption.java
Es verdad rafa, tienes razón creo que lo hemos planteado mal. Yo lo que pensaba era que en la vista se mostraran todas las adoption activas, pero si que es verdad que está mal planteado. 
Creo que deberíamos añadir otro boolean que se llame "admitted", false por defecto, que se cambie a true cuando el originalOwner acepte la adoption, entonces en el ejemplo que tu has puesto, al principio las 3 adoption tendrán su atributo active=true y el admitted=false, entonces cuando se acepte una de esas 3, las 3 pasaran a estar active=false y sólo una tendrá admitted=true, no sé si me he explicado.

2024-03-09 19:22 UTC, rafcarmed commented on src/main/java/org/springframework/samples/petclinic/adoption/Adoption.java
- Renombrada la clase `Adoptions` a `AdoptionsRequests`, para indicar más claramente que una fila en esta tabla representa una "Solicitud de adopción" de un newOwner sobre una mascota determinada, que finalmente acabará siendo Admitida o no. 
- Se añade el atributo `Boolean admitted` a la clase `AdoptionsRequests` que se marcará a `TRUE` para la fila/solicitud finalmente elegida por originalOwner como adoptante de su mascota.
- Se mantiene el atributo `Boolean active` para indicar con `TRUE` todas las solicitudes actualmente en proceso de adopción de una mascota determinada. Cuando finalice el proceso con una solicitud Admitida, todas las solicitudes abiertas para esta mascota se marcarán `active=FALSE` , con el fin de que no vuelvan a aparecer en otro proceso de adopción futuro sobre la misma mascota.

2024-03-10 09:53 UTC, Yato03 reviewed
Hola, he revisado tu pull request y me parece que has hecho un buen trabajo. Sin embargo, te sugiero que cambies la anotación @NotEmpty por @NotBlank en el atributo description de la clase AdoptionRequest. La razón es que @NotEmpty solo verifica que el string no sea vacío, pero no elimina los espacios en blanco al principio y al final. Esto significa que un valor como " " pasaría la validación, lo cual no es deseable. En cambio, @NotBlank hace un trim al string antes de comprobar su longitud, y así evita que se guarden valores con solo espacios en blanco en la base de datos. Creo que esto es más adecuado para el propósito de la aplicación.

2024-03-10 13:16 UTC, rafcarmed commented
Actualizado el cambio sugerido en tu revisión, Miguel, y subido a la rama remota. Gracias.

2024-03-10 16:30 UTC, Ramguerom reviewed
Creo que tras los cambios comentados por mis compañeros, lo veo todo correcto.

2024-03-10 21:43 UTC, benjimrfl reviewed
cambio minimo en la clase

2024-03-10 21:43 UTC, benjimrfl commented on src/main/java/org/springframework/samples/petclinic/adoption/AdoptionRequests.java
Rafa, una tontería de nada, la clase se debería llamar AdoptionRequest.

2024-03-10 21:44 UTC, benjimrfl reviewed
de acuerdo con estos cambios

2024-03-10 21:44 UTC, benjimrfl approved these changes

2024-03-11 11:17 UTC, Yato03 approved these changes

2024-03-11 11:37 UTC, Ramguerom approved these changes

2024-03-11 13:42 UTC, Davgodfer approved these changes
He estado echando un ojo y como dice ramón después de los cambios comentados por los compañeros, lo veo todo bien

2024-03-11 14:26 UTC, rafcarmed commented on src/main/java/org/springframework/samples/petclinic/adoption/AdoptionRequests.java
Cierto, Benji. Nombres de clase entidad en singular, la puse en plural como los nombres de tablas en BD por error.

Corregido y subido a rama remota. Gracias.

2024-03-11 14:30 UTC, merged